//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MGU.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MGU.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Border {
            get {
                object obj = ResourceManager.GetObject("Border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Close {
            get {
                object obj = ResourceManager.GetObject("Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseDisabled {
            get {
                object obj = ResourceManager.GetObject("CloseDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CloseHot {
            get {
                object obj = ResourceManager.GetObject("CloseHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClosePressed {
            get {
                object obj = ResourceManager.GetObject("ClosePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd&quot;&gt;
        ///&lt;HTML&gt;
        ///	&lt;HEAD&gt;
        ///        &lt;TITLE&gt;B.O.B.&apos;s SMR Tools&lt;/TITLE&gt;
        ///        &lt;META http-equiv=Content-Type content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///        &lt;META http-equiv=pragma content=no-cache&gt;
        ///
        ///        &lt;STYLE&gt;
        ///        
        ///            &lt;!--
        ///            
        ///                BODY
        ///                {
        ///                    PADDING-RIGHT: 10px;
        ///                    PADDING-LEFT: 10px;
        ///            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string header {
            get {
                return ResourceManager.GetString("header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Maximize {
            get {
                object obj = ResourceManager.GetObject("Maximize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaximizeDisabled {
            get {
                object obj = ResourceManager.GetObject("MaximizeDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaximizeHot {
            get {
                object obj = ResourceManager.GetObject("MaximizeHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MaximizePressed {
            get {
                object obj = ResourceManager.GetObject("MaximizePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimize {
            get {
                object obj = ResourceManager.GetObject("Minimize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MinimizeDisabled {
            get {
                object obj = ResourceManager.GetObject("MinimizeDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MinimizeHot {
            get {
                object obj = ResourceManager.GetObject("MinimizeHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MinimizePressed {
            get {
                object obj = ResourceManager.GetObject("MinimizePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd&quot;&gt;
        ///&lt;HTML&gt;
        ///	&lt;HEAD&gt;
        ///        &lt;TITLE&gt;B.O.B.&apos;s SMR Tools&lt;/TITLE&gt;
        ///        &lt;META http-equiv=Content-Type content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///        &lt;META http-equiv=pragma content=no-cache&gt;
        ///
        ///        &lt;STYLE&gt;
        ///        
        ///            &lt;!--
        ///            
        ///body,html {
        ///	height:100%;
        ///}
        ///
        ///body {
        ///	background:#0B2121;
        ///	font-family: Arial, sans-serif;
        ///	font-variant:normal;
        ///	margin:0px;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string miningInstructions {
            get {
                return ResourceManager.GetString("miningInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;
        ///                            &lt;br /&gt;
        ///                            &lt;h1&gt;Instructions:&lt;/h1&gt;
        ///                            &lt;ol&gt;
        ///                                &lt;li&gt;Open your webbrowser and goto www.smrealms.de/&lt;/li&gt;
        ///                                &lt;li&gt;Log into the game.&lt;/li&gt;
        ///                                &lt;li&gt;Enter the current game running.&lt;/li&gt;
        ///                                &lt;li&gt;Open your Alliance page.&lt;/li&gt;
        ///                                &lt;li&gt;
        ///                                    In the Alliance n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PBInstructions {
            get {
                return ResourceManager.GetString("PBInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd&quot;&gt;
        ///&lt;HTML&gt;
        ///	&lt;HEAD&gt;
        ///        &lt;TITLE&gt;B.O.B.&apos;s SMR Tools&lt;/TITLE&gt;
        ///        &lt;META http-equiv=Content-Type content=&quot;text/html; charset=iso-8859-1&quot;&gt;
        ///        &lt;META http-equiv=pragma content=no-cache&gt;
        ///
        ///        &lt;STYLE&gt;
        ///        
        ///            &lt;!--
        ///            
        ///body,html {
        ///	height:100%;
        ///}
        ///
        ///body {
        ///	background:#0B2121;
        ///	font-family: Arial, sans-serif;
        ///	font-variant:normal;
        ///	margin:0px;
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string planetBuildingInstructions {
            get {
                return ResourceManager.GetString("planetBuildingInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restore {
            get {
                object obj = ResourceManager.GetObject("Restore", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RestoreDisabled {
            get {
                object obj = ResourceManager.GetObject("RestoreDisabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RestoreHot {
            get {
                object obj = ResourceManager.GetObject("RestoreHot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RestorePressed {
            get {
                object obj = ResourceManager.GetObject("RestorePressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
